### PR TITLE
Issue 500 tm logo missing

### PR DESCRIPTION
**Pull request by tekgirl77**
Dependent on fix submitted in [PR](https://github.com/TeamMentor/TM_4_0_QA/pull/30) for [456](https://github.com/TeamMentor/TM_4_0_Design/issues/456)

### CODE REVIEW

**Comment by DinisCruz** [comment]
same as with the other one, can you update the PR?

**Comment by tekgirl77** [comment]
Done.  There were errors unrelated to this change on Travis... but it is [passing now](https://travis-ci.org/tekgirl77/TM_4_0_QA/builds/58208055), after re-running the tests a couple times.

**Comment by DinisCruz** [comment]
merged, @tekgirl77 this is really good stuff :) 

nice one, 

I really liked the fact that you were able to find a really good alternative to the **juice** api

**Comment by DinisCruz** [comment]
@tekgirl77, @michaelhidalgo  I moved the css tests into their own file so that they are easy to maintain (and we can put the dependencies at the top).

See https://github.com/TeamMentor/TM_4_0_QA/commit/ee8ede43353acf701628b8dcdbee57769974ab2d

**Pull request merged**
